"""Build a deterministic, self-contained Kaggle kernel package."""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import json
import zipfile
from pathlib import Path

PACKAGE_FILES = ("__init__.py", "corpus.py", "caption.py", "crosswalk.py", "smoke.py", "pipeline.py", "experiment.json")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def source_bundle(package_dir: Path) -> tuple[bytes, dict[str, str]]:
    entries: dict[str, bytes] = {}
    for name in PACKAGE_FILES:
        path = package_dir / name
        if not path.is_file():
            raise FileNotFoundError(f"package source missing: {path}")
        entries[f"visual_delta_fusion/{name}"] = path.read_bytes()
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for member, payload in sorted(entries.items()):
            info = zipfile.ZipInfo(member, date_time=(2020, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, payload)
    return buffer.getvalue(), {member: sha256_bytes(payload) for member, payload in entries.items()}


def runner_source(bundle: bytes, stage: str = "preflight") -> str:
    encoded = base64.b64encode(bundle).decode("ascii")
    return f'''"""Generated by visual_delta_fusion.package; do not edit manually."""
from __future__ import annotations
import base64
import io
import sys
import zipfile
from pathlib import Path

WORK = Path("/kaggle/working/visual_delta_fusion")
WORK.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{encoded}"))) as archive:
    archive.extractall(WORK)
PACKAGE_ROOT = WORK / "visual_delta_fusion"
sys.path.insert(0, str(WORK))
from visual_delta_fusion.pipeline import main
sys.argv = [sys.argv[0], "--stage", "{stage}", "--work-dir", str(PACKAGE_ROOT)]
main()
'''

def _extraction_cell(encoded_bundle: str) -> str:
    return f'''"""Generated by visual_delta_fusion.package; do not edit manually."""
import base64
import io
import sys
import zipfile
from pathlib import Path

WORK = Path("/kaggle/working/visual_delta_fusion")
WORK.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(io.BytesIO(base64.b64decode("{encoded_bundle}"))) as archive:
    archive.extractall(WORK)
PACKAGE_ROOT = WORK / "visual_delta_fusion"
sys.path.insert(0, str(WORK))
sys.path.insert(0, str(PACKAGE_ROOT))
print("extracted package to", PACKAGE_ROOT)
'''


PREFLIGHT_NOTEBOOK_CELLS: tuple[str, ...] = (
    '''from visual_delta_fusion.pipeline import run_preflight
result = run_preflight(PACKAGE_ROOT)
print(result["status"])
''',
)

# Each cell reuses tested building blocks from smoke.py/caption.py directly;
# the notebook only orchestrates and prints per-stage progress so a failure
# in one cell (e.g. Florence-2 load) still leaves every earlier cell's real
# output (metadata coverage, image download counts) visible in the pushed
# kernel version, instead of one opaque script traceback.
def _real_generation_notebook_cells(
    sample_call: str, stage: str, output_filename: str
) -> tuple[str, ...]:
    """Build the shared 9-cell real-generation notebook body, parameterized
    by the sample-selection call, stage name, and output filename. Used for
    both the 64-item smoke (`real_generator_smoke`) and the Phase 1 Step 6
    50-items-per-domain quality review (`quality_review`) — identical
    orchestration, different sample and output.
    """
    return (
        '''from caption import ensure_runtime_dependencies
resolved = ensure_runtime_dependencies()
print("pinned runtime dependencies:", resolved)
''',
        f'''import time
from pathlib import Path

from smoke import (
    select_smoke_sample, select_quality_review_sample, locate_mixed_root, load_asin_titles,
    fetch_domain_image_urls, download_image,
)
from caption import (
    CAPTION_MODEL_REVISION, CAPTION_MODEL_REVISION_FALLBACK,
    CAPTION_MAX_NEW_TOKENS, PARAPHRASE_MAX_NEW_TOKENS,
    Florence2Captioner, QwenParaphraser,
)

mixed_root = locate_mixed_root()
print("mixed_root =", mixed_root)
''',
        f'''sample = {sample_call}
print(f"sample size = {{len(sample)}}")
for domain, global_id in sample:
    print(f"  {{domain:26s}} {{global_id}}")
''',
        '''wanted_ids = {global_id for _domain, global_id in sample}
asin_titles = load_asin_titles(mixed_root, wanted_ids)
print(f"resolved {len(asin_titles)} of {len(wanted_ids)} sampled IDs to (asin, title)")
missing = sorted(wanted_ids - set(asin_titles))
print("no-asin catalog positions in this sample:", missing)
''',
        f'''records = []
by_domain = {{}}
for domain, global_id in sample:
    entry = asin_titles.get(global_id)
    if entry is None:
        records.append({{
            "domain": domain, "global_id": global_id, "asin": None, "title": None,
            "image_url": None, "image_status": "no_asin_in_catalog",
        }})
        continue
    asin, title = entry
    by_domain.setdefault(domain, []).append((global_id, asin, title))

# Scratch data lives under /kaggle/temp, never under the persisted
# /kaggle/working output; each domain meta_*.jsonl.gz is deleted right after
# its wanted ASINs are extracted (see ISSUES.md #9).
cache_dir = Path("/kaggle/temp/{stage}_metadata_cache")
image_dir = Path("/kaggle/temp/{stage}_images")
image_dir.mkdir(parents=True, exist_ok=True)

t0 = time.perf_counter()
for domain, entries in by_domain.items():
    wanted_asins = {{asin for _gid, asin, _title in entries}}
    t_domain = time.perf_counter()
    url_map = fetch_domain_image_urls(domain, wanted_asins, cache_dir)
    (cache_dir / f"meta_{{domain}}.jsonl.gz").unlink(missing_ok=True)
    print(f"{{domain}}: {{len(url_map)}}/{{len(wanted_asins)}} image URLs found in {{time.perf_counter()-t_domain:.1f}}s")
    for global_id, asin, title in entries:
        url = url_map.get(asin)
        records.append({{
            "domain": domain, "global_id": global_id, "asin": asin, "title": title,
            "image_url": url,
            "image_status": "missing_metadata" if url is None else "pending",
        }})
metadata_seconds = time.perf_counter() - t0
print(f"metadata streaming total: {{metadata_seconds:.1f}}s")
''',
        '''t0 = time.perf_counter()
for record in records:
    if record.get("image_status") != "pending":
        continue
    dest = image_dir / f"{record[\'global_id\']}.bin"
    outcome = download_image(str(record["image_url"]), dest)
    record["image_status"] = outcome["status"]
    if outcome["status"] == "decoded":
        record["image_path"] = outcome["path"]
        record["image_bytes"] = outcome["bytes"]
        record["image_sha256"] = outcome["sha256"]
    else:
        record["image_error"] = outcome.get("error")
download_seconds = time.perf_counter() - t0
decoded_count = sum(1 for r in records if r.get("image_status") == "decoded")
print(f"downloaded+decoded {decoded_count}/{len(records)} images in {download_seconds:.1f}s")
''',
        '''caption_items = [
    (record["global_id"], Path(str(record["image_path"])))
    for record in records if record.get("image_status") == "decoded"
]
t0 = time.perf_counter()
revision_used = CAPTION_MODEL_REVISION
revision_fallback_triggered = False
revision_error = None
try:
    captioner = Florence2Captioner(revision=CAPTION_MODEL_REVISION)
except Exception as exc:
    revision_error = f"{type(exc).__name__}: {exc}"
    revision_used = CAPTION_MODEL_REVISION_FALLBACK
    revision_fallback_triggered = True
    print("primary Florence-2 revision failed to load:", revision_error)
    captioner = Florence2Captioner(revision=CAPTION_MODEL_REVISION_FALLBACK)
caption_model_load_seconds = time.perf_counter() - t0
print(f"Florence-2 loaded (revision={revision_used}) in {caption_model_load_seconds:.1f}s")
''',
        '''t0 = time.perf_counter()
caption_results = captioner.caption_batch(caption_items)
caption_seconds = time.perf_counter() - t0
print(f"captioned {len(caption_results)} images in {caption_seconds:.1f}s "
      f"({caption_seconds/max(len(caption_results),1):.2f}s/image)")
caption_by_id = {r.item_id: r for r in caption_results}
for record in records:
    result = caption_by_id.get(record["global_id"])
    if result is None:
        continue
    record["caption_status"] = result.status
    record["caption_raw"] = result.raw_text
    record["caption_generated_tokens"] = result.generated_token_count
    record["caption_hit_token_cap"] = result.generated_token_count == CAPTION_MAX_NEW_TOKENS
for record in records:
    if "caption_raw" in record:
        print(record["domain"], record["global_id"], "->", record["caption_raw"])
''',
        '''paraphrase_items = [
    (record["global_id"], str(record["title"]))
    for record in records if record.get("title")
]
t0 = time.perf_counter()
paraphraser = QwenParaphraser()
paraphrase_model_load_seconds = time.perf_counter() - t0
print(f"Qwen2.5 paraphraser loaded in {paraphrase_model_load_seconds:.1f}s")
t0 = time.perf_counter()
paraphrase_results = paraphraser.paraphrase_batch(paraphrase_items)
paraphrase_seconds = time.perf_counter() - t0
print(f"paraphrased {len(paraphrase_results)} titles in {paraphrase_seconds:.1f}s")
paraphrase_by_id = {r.item_id: r for r in paraphrase_results}
for record in records:
    result = paraphrase_by_id.get(record["global_id"])
    if result is None:
        continue
    record["paraphrase_status"] = result.status
    record["paraphrase_text"] = result.raw_text
    record["paraphrase_generated_tokens"] = result.generated_token_count
    record["paraphrase_hit_token_cap"] = result.generated_token_count == PARAPHRASE_MAX_NEW_TOKENS
''',
        f'''import json

decoded_count = sum(1 for r in records if r.get("image_status") == "decoded")
captioned_ok = sum(1 for r in records if r.get("caption_status") == "ok")
paraphrased_ok = sum(1 for r in records if r.get("paraphrase_status") == "ok")
caption_cap_hits = sum(1 for r in records if r.get("caption_hit_token_cap"))
paraphrase_cap_hits = sum(1 for r in records if r.get("paraphrase_hit_token_cap"))

result = {{
    "status": "PASS" if decoded_count > 0 and captioned_ok > 0 and paraphrased_ok > 0 else "FAIL",
    "stage": "{stage}",
    "sample_size": len(sample),
    "domains_sampled": sorted(by_domain),
    "image_coverage": decoded_count / len(sample),
    "caption_ok_rate": captioned_ok / max(decoded_count, 1),
    "caption_token_cap_hit_rate": caption_cap_hits / max(decoded_count, 1),
    "paraphrase_ok_rate": paraphrased_ok / max(len(paraphrase_items), 1),
    "paraphrase_token_cap_hit_rate": paraphrase_cap_hits / max(len(paraphrase_items), 1),
    "caption_model_revision_used": revision_used,
    "caption_model_revision_fallback_triggered": revision_fallback_triggered,
    "caption_model_revision_primary_error": revision_error,
    "timing_seconds": {{
        "metadata_stream": metadata_seconds,
        "image_download": download_seconds,
        "caption_model_load": caption_model_load_seconds,
        "caption_generation_total": caption_seconds,
        "caption_generation_per_image": caption_seconds / max(decoded_count, 1),
        "paraphrase_model_load": paraphrase_model_load_seconds,
        "paraphrase_generation_total": paraphrase_seconds,
        "paraphrase_generation_per_item": paraphrase_seconds / max(len(paraphrase_items), 1),
    }},
    "records": records,
}}
(PACKAGE_ROOT / "{output_filename}").write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
print(json.dumps({{key: value for key, value in result.items() if key != "records"}}, indent=2, sort_keys=True))
''',
    )


def _paraphrase_probe_notebook_cells(model_id: str, revision: str, output_filename: str) -> tuple[str, ...]:
    """Lean paraphraser-only comparison: skips metadata streaming, image
    download, and Florence-2 captioning entirely (paraphrasing is
    title-only). See plans/260915-0955-visual-delta-fusion-pilot/ISSUES.md
    #15 for why this comparison is needed.
    """
    return (
        '''from caption import ensure_runtime_dependencies
resolved = ensure_runtime_dependencies()
print("pinned runtime dependencies:", resolved)
''',
        f'''from smoke import locate_mixed_root, run_paraphrase_probe

mixed_root = locate_mixed_root()
print("mixed_root =", mixed_root)
result = run_paraphrase_probe(
    PACKAGE_ROOT, mixed_root,
    model_id="{model_id}", revision="{revision}",
    output_filename="{output_filename}",
)
''',
        '''for record in result["records"]:
    if record.get("paraphrase_text"):
        print(record["domain"], "|", record["title"][:60])
        print("   ->", record["paraphrase_text"])
''',
    )


REAL_GENERATOR_SMOKE_NOTEBOOK_CELLS: tuple[str, ...] = _real_generation_notebook_cells(
    "select_smoke_sample()", "real_generator_smoke", "smoke_results.json"
)

QUALITY_REVIEW_NOTEBOOK_CELLS: tuple[str, ...] = _real_generation_notebook_cells(
    "select_quality_review_sample()", "quality_review", "quality_review_results.json"
)

# Candidate control model for ISSUES.md #15 option 1 ("larger paraphraser
# model"). Resolved from the live HF API 2026-09-15
# (https://huggingface.co/api/models/Qwen/Qwen2.5-3B-Instruct): sha
# aa8e72537993ba99e69dfaafa59ed015b17504d1. License is "qwen-research", not
# apache-2.0 like the pinned 0.5B default — a real constraint if this
# candidate is ever adopted, not just a test detail.
PARAPHRASE_PROBE_3B_NOTEBOOK_CELLS: tuple[str, ...] = _paraphrase_probe_notebook_cells(
    "Qwen/Qwen2.5-3B-Instruct", "aa8e72537993ba99e69dfaafa59ed015b17504d1",
    "paraphrase_probe_3b_results.json",
)

_LOCAL_MODULE_NAMES = ("corpus", "caption", "crosswalk", "smoke", "pipeline")


def _strip_local_imports(source: str) -> str:
    """Remove intra-package `import X` / `from X import ...` lines (single-
    or multi-line parenthesized) referencing this package's own sibling
    modules, keeping every other line byte-for-byte identical.

    Used to inline a tested module's real source directly as a plain
    notebook cell: once an earlier cell has executed a sibling module's
    source into the shared notebook namespace, its names are already
    defined, so the cross-module import line would be both unnecessary and
    unresolvable (there is no real `crosswalk` package on Kaggle in inline
    mode, only the executed cell's globals).
    """
    local_prefixes = tuple(f"from {name} import" for name in _LOCAL_MODULE_NAMES) + tuple(
        f"import {name}" for name in _LOCAL_MODULE_NAMES
    )
    lines = source.splitlines(keepends=True)
    kept: list[str] = []
    index = 0
    while index < len(lines):
        stripped = lines[index].strip()
        if stripped.startswith(local_prefixes):
            if "(" in stripped and ")" not in stripped:
                index += 1
                while index < len(lines) and ")" not in lines[index]:
                    index += 1
                index += 1
            else:
                index += 1
            continue
        kept.append(lines[index])
        index += 1
    return "".join(kept)


def _module_cell(package_dir: Path, name: str) -> str:
    """Return one sibling module's real source, ready to run as a plain
    notebook cell with zero zip/base64 wrapping (see ISSUES.md #23)."""
    source = (package_dir / name).read_text(encoding="utf-8")
    return _strip_local_imports(source)


def _full_corpus_inline_cells(package_dir: Path) -> tuple[str, ...]:
    """Genuinely separate, directly-editable notebook cells for full-catalog
    generation: no embedded zip archive, no base64, no opaque single-cell
    `main()` call. Each dependency module is its own cell of real, tested
    source; the remaining cells orchestrate deps, metadata resolution, the
    checkpointed/resumable generation loop, and arm assembly, mirroring the
    step granularity already used by the smoke/quality-review notebooks.
    A failed or cancelled run can be re-pushed as-is: `process_catalog_
    records_incrementally` resumes from its last on-disk shard checkpoint
    instead of restarting from item 0.
    """
    return (
        _module_cell(package_dir, "corpus.py"),
        _module_cell(package_dir, "crosswalk.py"),
        _module_cell(package_dir, "caption.py"),
        _module_cell(package_dir, "smoke.py"),
        '''import time

KERNEL_START = time.perf_counter()
resolved = ensure_runtime_dependencies()
print("pinned runtime dependencies:", resolved)
''',
        '''mixed_root = locate_mixed_root()
print("mixed_root =", mixed_root)
_titles, metadata_records = resolve_full_catalog_metadata(mixed_root)
print(f"metadata resolved for {len(metadata_records)} catalog items")
''',
        '''import hashlib
import json
import shutil
import time
from pathlib import Path

WORK_DIR = Path("/kaggle/working")
TEMP_DIR = Path("/kaggle/temp")
OUT_DIR = WORK_DIR / "full_corpus"
IMAGE_DIR = TEMP_DIR / "full_corpus_images"
IMAGE_DIR.mkdir(parents=True, exist_ok=True)

# /kaggle/working starts empty on every single push; a checkpoint written
# by an earlier version of THIS SAME kernel only survives if that version's
# output is mounted as a `kernel_sources` input (self-reference) and copied
# back into /kaggle/working here. Located by filename, not by an assumed
# mount path, per rule://kaggle-mcp-experiments. The first push has no
# kernel_sources yet, so this is a no-op and generation starts from item 0.
#
# Real cross-push resumes (ISSUES.md #29-#31) hit a reproducible failure on
# one specific shard file: the copied local bytes hashed correctly at one
# read and then failed to parse moments later, on the exact same shard,
# across three separate pushes. Retrying the *local* read alone (issues
# #29, #30) never fixed it, because the flaw is in the copy from
# `/kaggle/input`, not in re-reading what was already copied. This cell now
# hash-verifies every shard file immediately after copying it and, on
# mismatch, re-copies fresh bytes from the source mount (not the possibly
# bad local file) up to 3 times before giving up.
prior_manifests = sorted(Path("/kaggle/input").glob("**/full_corpus/shard-manifest.json"))
if prior_manifests:
    prior_dir = prior_manifests[0].parent
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    prior_manifest = json.loads(prior_manifests[0].read_text(encoding="utf-8"))
    expected_hash_by_name = {shard["path"]: shard["sha256"] for shard in prior_manifest.get("shards", [])}
    verified = 0
    for item in prior_dir.iterdir():
        dest = OUT_DIR / item.name
        expected_hash = expected_hash_by_name.get(item.name)
        for copy_attempt in range(3):
            shutil.copy2(item, dest)
            if expected_hash is None:
                break
            actual_hash = hashlib.sha256(dest.read_bytes()).hexdigest()
            if actual_hash == expected_hash:
                verified += 1
                break
            print(f"resume-copy: {item.name} hash mismatch on copy attempt {copy_attempt + 1}/3, re-copying from source")
            if copy_attempt < 2:
                time.sleep(1.0)
        else:
            raise RuntimeError(
                f"resume-copy: {item.name} still fails hash verification after 3 fresh "
                "copies from /kaggle/input; the source mount itself is unreliable for this file"
            )
    shard_count = len(list(OUT_DIR.glob("shard-*.jsonl")))
    print(f"resume: copied and hash-verified {verified} shard file(s) from {prior_dir} ({shard_count} total)")
else:
    print("resume: no prior checkpoint found under /kaggle/input; starting from item 0")
''',
        '''captioner = Florence2Captioner(revision=CAPTION_MODEL_REVISION)
paraphraser = QwenParaphraser(model_id=PARAPHRASE_MODEL_ID, revision=PARAPHRASE_MODEL_REVISION)

def resolve_image(record, image_dir):
    dest = image_dir / f"{record[\'global_id\']}.bin"
    return download_image(str(record["image_url"]), dest)

# Kaggle enforces a hard ~21,600s (6h) script execution cap (see
# ISSUES.md #22/#24). This budget is measured from KERNEL_START (before
# dependency pinning and metadata streaming), not from this cell, so an
# unexpectedly slow earlier stage automatically leaves less time here
# instead of overrunning the platform's own timeout. 19,800s = 5.5h leaves
# a 30-minute margin for final checkpoint flush and shutdown.
TIME_BUDGET_SECONDS = 19800.0
DEADLINE = KERNEL_START + TIME_BUDGET_SECONDS

IDENTITY = {
    "stage": "full_corpus_generation",
    "catalog_size": CATALOG_SIZE,
    "paraphrase_model": PARAPHRASE_MODEL_ID,
    "paraphrase_revision": PARAPHRASE_MODEL_REVISION,
    "caption_revision": CAPTION_MODEL_REVISION,
    "shuffle_seed": 7001,
    "shard_size": 512,
}

# Conservative first value for T4 VRAM (Florence-2-large + Qwen2.5-3B both
# resident simultaneously); not part of `IDENTITY` since it only affects
# throughput, never the generated captions/paraphrases themselves — safe to
# change between resumed pushes without invalidating the checkpoint.
BATCH_SIZE = 8

records = process_catalog_records_incrementally(
    metadata_records, captioner, paraphraser, OUT_DIR, IDENTITY, IMAGE_DIR, resolve_image,
    shard_size=512, deadline=DEADLINE, batch_size=BATCH_SIZE,
)
print(f"generation complete: {len(records)}/{len(metadata_records)} records")
if len(records) < len(metadata_records):
    print("TIME BUDGET REACHED: add this kernel's own slug to kernel_sources and "
          "re-push the identical notebook to resume from the checkpoint above.")
''',
        '''import ast
import csv
import json

if len(records) < len(metadata_records):
    print(f"skipping arm assembly: only {len(records)}/{len(metadata_records)} records generated so far; "
          "re-push this identical kernel to resume and finish generation before building arms")
else:
    train_files = sorted((mixed_root / "train").glob("*.csv"))
    sequences = []
    for path in train_files:
        with path.open(encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                try:
                    sequences.append([int(value) for value in ast.literal_eval(row["history_item_id"])])
                except (KeyError, SyntaxError, ValueError):
                    continue
    frequencies = compute_training_frequencies(sequences)
    real_cues = {r["global_id"]: r["caption_raw"] for r in records if r.get("caption_status") == "ok"}
    paraphrase_cues = {r["global_id"]: r["paraphrase_text"] for r in records if r.get("paraphrase_status") == "ok"}
    donor_map = frequency_bin_derangement(sorted(real_cues), frequencies, seed=7001)
    rows = [
        CatalogRow(
            domain=str(record["domain"]), source_item_id=str(record["global_id"]),
            downstream_item_id=record["global_id"], parent_asin=record.get("asin"),
            source_title=str(record["title"]), order_index=record["global_id"],
            image_status=str(record.get("image_status", "unknown")),
            caption_status=str(record.get("caption_status", "unknown")),
            raw_caption=record.get("caption_raw"),
        )
        for record in records
    ]
    arms = build_arms(rows, real_cues, paraphrase_cues, donor_map)
    for record, arm in zip(records, arms):
        record["arm_texts"] = arm.texts
        record["shuffle_donor_id"] = arm.shuffle_donor_id

    manifest = write_sharded_records(records, OUT_DIR, IDENTITY, shard_size=512)
    manifest["available_caption_count"] = len(real_cues)
    manifest["image_decoded_count"] = sum(record.get("image_status") == "decoded" for record in records)
    manifest["paraphrase_ok_count"] = sum(record.get("paraphrase_status") == "ok" for record in records)
    (WORK_DIR / "full_corpus_summary.json").write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({k: v for k, v in manifest.items() if k != "shards"}, indent=2, sort_keys=True))
''',
    )


# Stages needing zero zip/base64 wrapping: their cell-generating callable
# receives the real package directory and inlines tested sibling-module
# source directly, so the pushed kernel is fully readable/editable in the
# Kaggle notebook UI without regenerating from a local source bundle.
INLINE_STAGES = {"full_corpus_generation"}

NOTEBOOK_STAGE_CELLS: dict[str, tuple[str, ...]] = {
    "preflight": PREFLIGHT_NOTEBOOK_CELLS,
    "real_generator_smoke": REAL_GENERATOR_SMOKE_NOTEBOOK_CELLS,
    "quality_review": QUALITY_REVIEW_NOTEBOOK_CELLS,
    "paraphrase_probe_3b": PARAPHRASE_PROBE_3B_NOTEBOOK_CELLS,
    "full_corpus_generation": _full_corpus_inline_cells,
}


def _code_cell(source: str) -> dict[str, object]:
    lines = source.splitlines(keepends=True)
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}


def notebook_source(bundle: bytes, stage: str, package_dir: Path | None = None) -> str:
    if stage not in NOTEBOOK_STAGE_CELLS:
        raise ValueError(f"no notebook cells registered for stage {stage!r}")
    entry = NOTEBOOK_STAGE_CELLS[stage]
    if stage in INLINE_STAGES:
        cell_bodies = entry(package_dir or Path(__file__).parent)
        cells = [_code_cell(body) for body in cell_bodies]
    else:
        encoded = base64.b64encode(bundle).decode("ascii")
        cells = [_code_cell(_extraction_cell(encoded))]
        cells.extend(_code_cell(body) for body in entry)
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1)

def write_kernel_package(
    package_dir: Path,
    output_dir: Path,
    kernel_id: str,
    title: str,
    stage: str = "preflight",
    dataset_sources: list[str] | None = None,
    kernel_sources: list[str] | None = None,
    notebook: bool = False,
) -> dict[str, object]:
    bundle, member_hashes = source_bundle(package_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if notebook:
        code_file = "runner.ipynb"
        runner = notebook_source(bundle, stage=stage, package_dir=package_dir).encode("utf-8")
    else:
        code_file = "runner.py"
        runner = runner_source(bundle, stage=stage).encode("utf-8")
    (output_dir / code_file).write_bytes(runner)
    metadata = {
        "id": kernel_id,
        "title": title,
        "code_file": code_file,
        "language": "python",
        "kernel_type": "notebook" if notebook else "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_tpu": False,
        "enable_internet": True,
        "keywords": [],
        "dataset_sources": list(dataset_sources or []),
        "kernel_sources": list(kernel_sources or []),
        "competition_sources": [],
        "model_sources": [],
        "machine_shape": "NvidiaTeslaT4",
    }
    (output_dir / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    manifest = {
        "stage": stage,
        "notebook": notebook,
        "bundle_sha256": sha256_bytes(bundle),
        "runner_sha256": sha256_bytes(runner),
        "members": member_hashes,
        "metadata_sha256": sha256_bytes((output_dir / "kernel-metadata.json").read_bytes()),
    }
    (output_dir / "package-manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--package-dir", type=Path, default=Path(__file__).parent)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--kernel-id", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--stage", default="preflight")
    parser.add_argument("--dataset-sources", default="", help="comma-separated Kaggle dataset refs to mount")
    parser.add_argument("--kernel-sources", default="", help="comma-separated Kaggle kernel refs to mount (self-reference to resume from a prior push's output)")
    parser.add_argument("--notebook", action="store_true", help="emit runner.ipynb (kernel_type=notebook) instead of runner.py")
    args = parser.parse_args()
    dataset_sources = [item for item in args.dataset_sources.split(",") if item]
    kernel_sources = [item for item in args.kernel_sources.split(",") if item]
    print(json.dumps(
        write_kernel_package(
            args.package_dir, args.output_dir, args.kernel_id, args.title,
            stage=args.stage, dataset_sources=dataset_sources, kernel_sources=kernel_sources,
            notebook=args.notebook,
        ),
        indent=2, sort_keys=True,
    ))



if __name__ == "__main__":
    main()
